-- =====================================================================
-- V1: 초기 스키마
-- Flyway 가 애플리케이션 시작 시 한 번만 실행하고, 실행 이력은 flyway_schema_history 테이블에 남는다.
-- 이미 적용된 파일은 절대 수정하지 않는다. 변경이 필요하면 V2__*.sql 을 새로 추가한다.
-- =====================================================================

CREATE TABLE users
(
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name       VARCHAR(50)  NOT NULL,
    email      VARCHAR(100) NOT NULL,
    password   VARCHAR(100) NOT NULL, -- BCrypt 해시 (원문 비밀번호는 저장하지 않음)
    department VARCHAR(50),
    role       VARCHAR(20)  NOT NULL,
    created_at TIMESTAMP(6) NOT NULL,
    updated_at TIMESTAMP(6) NOT NULL,
    CONSTRAINT uk_users_email UNIQUE (email)
);

CREATE TABLE asset
(
    id               BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name             VARCHAR(100) NOT NULL,
    type             VARCHAR(20)  NOT NULL,
    serial_number    VARCHAR(50)  NOT NULL,
    status           VARCHAR(20)  NOT NULL,
    assigned_user_id BIGINT REFERENCES users (id),
    purchased_at     DATE,
    memo             VARCHAR(500),
    version          BIGINT,
    created_at       TIMESTAMP(6) NOT NULL,
    updated_at       TIMESTAMP(6) NOT NULL,
    CONSTRAINT uk_asset_serial_number UNIQUE (serial_number)
);

CREATE INDEX idx_asset_status ON asset (status);
CREATE INDEX idx_asset_assigned_user ON asset (assigned_user_id);

CREATE TABLE ticket
(
    id                    BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    title                 VARCHAR(100)  NOT NULL,
    description           VARCHAR(2000) NOT NULL,
    category              VARCHAR(20)   NOT NULL,
    priority              VARCHAR(20)   NOT NULL,
    classification_source VARCHAR(20)   NOT NULL,
    status                VARCHAR(20)   NOT NULL,
    requester_id          BIGINT        NOT NULL REFERENCES users (id),
    assignee_id           BIGINT REFERENCES users (id),
    asset_id              BIGINT REFERENCES asset (id),
    due_at                TIMESTAMP(6)  NOT NULL,
    resolved_at           TIMESTAMP(6),
    version               BIGINT,
    created_at            TIMESTAMP(6)  NOT NULL,
    updated_at            TIMESTAMP(6)  NOT NULL
);

CREATE INDEX idx_ticket_status ON ticket (status);
CREATE INDEX idx_ticket_assignee ON ticket (assignee_id);
CREATE INDEX idx_ticket_requester ON ticket (requester_id);

CREATE TABLE ticket_history
(
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    ticket_id   BIGINT       NOT NULL REFERENCES ticket (id),
    actor_id    BIGINT REFERENCES users (id), -- 처리자 (누가 변경했는지)
    from_status VARCHAR(20),
    to_status   VARCHAR(20)  NOT NULL,
    note        VARCHAR(500),
    created_at  TIMESTAMP(6) NOT NULL,
    updated_at  TIMESTAMP(6) NOT NULL
);

CREATE INDEX idx_ticket_history_ticket ON ticket_history (ticket_id);

-- 로그인 유지용 refresh token. 원문이 아닌 SHA-256 해시만 저장한다.
CREATE TABLE refresh_token
(
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id    BIGINT       NOT NULL REFERENCES users (id) ON DELETE CASCADE,
    token_hash VARCHAR(64)  NOT NULL,
    expires_at TIMESTAMP(6) NOT NULL,
    created_at TIMESTAMP(6) NOT NULL,
    updated_at TIMESTAMP(6) NOT NULL,
    CONSTRAINT uk_refresh_token_hash UNIQUE (token_hash)
);

CREATE INDEX idx_refresh_token_user ON refresh_token (user_id);
