-- =====================================================================
-- V3: 티켓 댓글 / 첨부파일
-- =====================================================================

CREATE TABLE ticket_comment
(
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    ticket_id  BIGINT        NOT NULL REFERENCES ticket (id),
    author_id  BIGINT        NOT NULL REFERENCES users (id),
    content    VARCHAR(2000) NOT NULL,
    internal   BOOLEAN       NOT NULL DEFAULT FALSE, -- IT 관리자끼리만 보는 내부 메모
    created_at TIMESTAMP(6)  NOT NULL,
    updated_at TIMESTAMP(6)  NOT NULL
);

CREATE INDEX idx_ticket_comment_ticket ON ticket_comment (ticket_id);

CREATE TABLE ticket_attachment
(
    id                BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    ticket_id         BIGINT       NOT NULL REFERENCES ticket (id),
    uploader_id       BIGINT       NOT NULL REFERENCES users (id),
    original_filename VARCHAR(255) NOT NULL, -- 화면 표시·다운로드용 (저장 경로에는 절대 사용하지 않음)
    stored_name       VARCHAR(100) NOT NULL, -- 서버가 만든 UUID 파일명
    content_type      VARCHAR(100) NOT NULL, -- 서버가 확장자로 결정한 값 (클라이언트 값 신뢰 안 함)
    size_bytes        BIGINT       NOT NULL,
    created_at        TIMESTAMP(6) NOT NULL,
    updated_at        TIMESTAMP(6) NOT NULL,
    CONSTRAINT uk_ticket_attachment_stored_name UNIQUE (stored_name)
);

CREATE INDEX idx_ticket_attachment_ticket ON ticket_attachment (ticket_id);
