-- =====================================================================
-- V4: 알림 / SLA 임박·초과 알림 발송 기록
-- =====================================================================

CREATE TABLE notification
(
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    recipient_id BIGINT       NOT NULL REFERENCES users (id) ON DELETE CASCADE,
    ticket_id    BIGINT REFERENCES ticket (id) ON DELETE CASCADE,
    type         VARCHAR(30)  NOT NULL,
    message      VARCHAR(300) NOT NULL,
    read_at      TIMESTAMP(6),
    created_at   TIMESTAMP(6) NOT NULL,
    updated_at   TIMESTAMP(6) NOT NULL
);

-- "내 안 읽은 알림" 조회용
CREATE INDEX idx_notification_recipient ON notification (recipient_id, read_at);

-- 같은 기한에 대해 알림을 두 번 보내지 않도록 발송 시각을 기록 (재분류로 기한이 바뀌면 초기화)
ALTER TABLE ticket ADD COLUMN sla_warned_at TIMESTAMP(6);
ALTER TABLE ticket ADD COLUMN sla_breached_at TIMESTAMP(6);

CREATE INDEX idx_ticket_due_at ON ticket (due_at);
