-- =====================================================================
-- V6: SNS 로그인 (Google / Kakao / Naver)
-- =====================================================================

-- SNS 전용 회원은 비밀번호가 없다
ALTER TABLE users ALTER COLUMN password DROP NOT NULL;

CREATE TABLE user_social_account
(
    id               BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id          BIGINT       NOT NULL REFERENCES users (id),
    provider         VARCHAR(20)  NOT NULL, -- GOOGLE, KAKAO, NAVER
    provider_user_id VARCHAR(255) NOT NULL, -- 제공자가 주는 고유 id (Google sub, Kakao id, Naver id)
    created_at       TIMESTAMP(6) NOT NULL,
    updated_at       TIMESTAMP(6) NOT NULL,
    CONSTRAINT uk_social_provider_user UNIQUE (provider, provider_user_id), -- 같은 SNS 계정은 한 번만 가입
    CONSTRAINT uk_social_user_provider UNIQUE (user_id, provider)           -- 한 회원은 제공자별로 1개만 연결
);

CREATE INDEX idx_social_account_user ON user_social_account (user_id);